services:
  server:
    build:
      context: ./server
    container_name: server
    ports:
      - '3001:3001'
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - aroundu-network

  web:
    build:
      context: ./web
    container_name: web
    ports:
      - '3000:3000'
    volumes:
      - ./web:/app
      - /app/node_modules
    networks:
      - aroundu-network

networks:
  aroundu-network:
    driver: bridge
